"""Changed a column

Revision ID: 8d671ae598d3
Revises: 11d0a904e4db
Create Date: 2024-04-01 18:00:21.205502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d671ae598d3'
down_revision: Union[str, None] = '11d0a904e4db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_col', sa.Column('IP', sa.String(length=30), nullable=True))
    op.drop_column('test_col', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_col', sa.Column('name', sa.VARCHAR(length=30), nullable=False))
    op.drop_column('test_col', 'IP')
    # ### end Alembic commands ###
